name: scholaris
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.17.2
  go_router: ^14.0.0
  flutter_riverpod: ^2.5.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  google_fonts: ^6.2.1
  lottie: ^3.5.1
  shared_preferences: ^2.5.5
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: 4.0.0
  json_serializable: 6.14.1
  build_runner: 2.15.3

flutter:
  uses-material-design: true
  assets:
    - assets/animations/scholaris_ceremony.json
    - assets/animations/onboarding_slide1.json
    - assets/animations/onboarding_slide2.json
    - assets/animations/onboarding_slide3.json
    - assets/animations/Sign up.json
    - assets/animations/login_hero.json
    - assets/animations/Forgot password.json
    - assets/images/scholaris_hero_student.png
    - assets/images/onboarding_slide1.svg
    - assets/images/onboarding_slide2.svg
    - assets/images/onboarding_slide3.svg
    - assets/images/login_hero.svg
